CREATE DATABASE IF NOT EXISTS organization_db;
CREATE DATABASE IF NOT EXISTS employee_db;
CREATE DATABASE IF NOT EXISTS leave_db;
CREATE DATABASE IF NOT EXISTS recruitment_db;
CREATE DATABASE IF NOT EXISTS training_db;
CREATE DATABASE IF NOT EXISTS hr_planning_db;
CREATE DATABASE IF NOT EXISTS auth_db;