server:
  port: 8188

spring:
  application:
    name: transfer-service

  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8888}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: ${MYSQL_DB_URL:jdbc:mysql://localhost:3306/transfer_db}?createDatabaseIfNotExist=true
    username: ${MYSQL_DB_USERNAME:root}
    password: ${MYSQL_DB_PASSWORD:mysql}
    driver-class-name: com.mysql.cj.jdbc.Driver
