server:
  port: 8761

spring:
  application:
    name: discovery-server

eureka:
  instance:
     preferIpAddress: true
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${HOSTNAME:localhost}:8761/eureka/

management:
  tracing:
     sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always